name: layout_practice
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  link: ^1.0.0
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  intl: ^0.15.2
  google_maps_flutter: ^0.4.0
  location: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/lzmgroupphoto.jpg
    - images/doubleslogo.png
    - images/capitalagroup.jpg
    - images/savannahjazzfest.jpg
    - images/studioboard.jpg
    - images/thedooverscreenshot.png
    - images/berniesanders1.jpg
    - images/elansavannah1.jpg
    - images/joebiden1.jpg
    - images/lzmbuyerphoto.jpg
    - images/infinitus1.jpg
    - images/wsavgroup.jpg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans-Regular.ttf
        - asset: fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Permanent Marker
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
        - asset: fonts/JosefinSans-RegularItalic.ttf
          style: italic
        - asset: fonts/JosefinSans-Bold.ttf
          weight: 800
        - asset: fonts/JosefinSans-BoldItalic.ttf
          style: italic
          weight: 800
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
